# Generated by Django 5.0.6 on 2024-05-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='title',
            new_name='symbol',
        ),
    ]
